export const { PORT } = process.env
export const { SECRET_KEY } = process.env
export const { DB_URL } = process.env
export const { WVC_URL } = process.env
export const { WVC_KEY } = process.env
export const { API_KEY_OPEN_WEATHER } = process.env
export const { BASE_URL_GEOLOCATION } = process.env
export const SALT_LENGTH = 5
export const JWT_TOKEN_LIFE_TIME = '24h'
