export const TABLE_BTN_TEXT = 'table'
export const MAP_BTN_TEXT = 'map'
export const GRAPH_BTN_TEXT = 'graph'
export const DEGREES_CELSIUS = '°C'
export const DEGREES_FAHRENHEIT = '°F'
export const KEY_UNITS_IN_LOCAL_STORAGE = 'units'
export const KEY_TOKEN_IN_LOCAL_STORAGE = 'token'
